### ISSUE TITLE
[BUG] Docker -- anyscale/ray-llm:latest is essentially 0.3.0

### ISSUE THREAD

**Issue by JGSweets** [ray-project/ray-llm#122]
When trying to run the docker image remotely on AWS, the Mixtral models fails to deploy due to the image being out of date with respect to the repository cluster config using latest as opposed to the tag.

https://hub.docker.com/r/anyscale/ray-llm/tags
https://github.com/ray-project/ray-llm/blob/v0.5.0/deploy/ray/rayllm-cluster.yaml#L10

**Comment by sihanwang41** [comment]
Hi @JGSweets , thank for raising the issue! I have already updated the latest image.
